### ISSUE TITLE
requesting for dataset

### ISSUE THREAD

**Issue by salhasalman** [andrewjohnaj/NLP-AuthorPrediction-WebApp#21]
@andrewjohnaj can i get the link to dataset
Thanks

**Comment by andrewjohnaj** [comment]
Hi Salha, attaching the train and test data files used in the project. Hope this helps!

Best regards,
Andrew

[train_set.csv](https://github.com/user-attachments/files/17346682/train_set.csv)
[source_mapping.txt](https://github.com/user-attachments/files/17346683/source_mapping.txt)
[test_set.csv](https://github.com/user-attachments/files/17346684/test_set.csv)

> @andrewjohnaj can i get the link to dataset Thanks
